In [1]:
#Data Pre-procesing Step  
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  
    

In [2]:
#importing datasets  
data_set= pd.read_csv('/content/sample_data/user.csv')  

In [27]:
# Import label encoder
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'gender'.
data_set['GENDER']= label_encoder.fit_transform(data_set['GENDER'])
  
data_set['GENDER'].unique()

array([0, 1])

In [28]:
data_set

USERID  GENDER  AGE  SALARY  PURCHASED
0      12       0   20   26000          0
1     123       0   30   47000          1
2      44       1   40   45000          0
3      88       1   50   28000          1

In [29]:
#Extracting Independent and dependent Variable  
x= data_set.iloc[:, [1,2,3]].values  
y= data_set.iloc[:, 4].values  

In [30]:
print(x) #age and salary

[[    0    20 26000]
 [    0    30 47000]
 [    1    40 45000]
 [    1    50 28000]]


In [9]:
print(y) #PURCHASED

[0 1 0 1]


In [31]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25)  

In [32]:
#Fitting Logistic Regression to the training set  
from sklearn.linear_model import LogisticRegression  
classifier= LogisticRegression()  
classifier.fit(x_train, y_train)  

LogisticRegression()

In [33]:
#Predicting the test set result  
y_pred= classifier.predict(x_test)  

In [34]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
cm

array([[0, 0],
       [1, 0]])

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

1.0

In [47]:
#Extracting Independent and dependent Variable  
x= data_set.iloc[:, [2,3]].values  
y= data_set.iloc[:, 1].values 

print(x)
print(y)

# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2) 


#Fitting Logistic Regression to the training set  
from sklearn.linear_model import LogisticRegression  


classifier= LogisticRegression()  
classifier.fit(x_train, y_train)  

#Predicting the test set result  
y_pred= classifier.predict(x_test)  


from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
cm


[[   20 26000]
 [   30 47000]
 [   40 45000]
 [   50 28000]]
[0 0 1 1]


array([[1]])

In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

1.0