In [5]:
import numpy as np

In [15]:
a= np.array(['FCAIT','FCT','FET'])

print(type(a))

print(a)

<class 'numpy.ndarray'>
['FCAIT' 'FCT' 'FET']


In [3]:
b = np.arange(0,10,1)

print(b)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
c = np.zeros(3)

print(c)

c1 = np.zeros((3,3)) #have to give as tuple

print(c1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:


c1 = np.ones((4,3)) #have to give as tuple

print(c1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
b = np.eye(5)
b


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
c = np.linspace(0,1,11)

print(c)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [23]:

l = [1,5,3,8,2,3,6,7,5,2,9,11,2,5,3,4,8,9,3,1,9,3]

a = np.array(l)

print(a.max())



11


In [28]:
l = [1,5,3,8,2,3,6,7,5,2,9,11,2,5,3,4,8,9,3,1,9,3]

a = np.array(l)

print('Max way1 = ',a.max())

print('Max way2 = ',np.min(a))

Max way1 =  11
Max way2 =  1


In [25]:
l = [7,5,3,1,8,2,3,6,11,5,2,9,10,2,5,3,7,8,9,3,1,9,3]

a = np.array(l)

#print('Min = ',a.min())

print('ArgMin = ',a.argmin())

#print('Max = ',a.max())

print('ArgMax = ',a.argmax())

print('Sum = ',a.sum())

print('Mean = ',a.mean())

print('Std = ',a.std())

ArgMin =  3
ArgMax =  8
Sum =  122
Mean =  5.304347826086956
Std =  3.042235771223635


In [26]:
ar = np.array([1,1,3])

print(ar.sum())

5


In [27]:

array2d = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

print('sum (cols)= ',array2d.sum(axis=0)) #Vertical

print('sum (rows)= ',array2d.sum(axis=1)) #Horizontal


sum (cols)=  [12 15 18]
sum (rows)=  [ 6 15 24]


In [35]:
b = np.zeros((5,5))

c=b.reshape(1,2)

print(c)

ValueError: cannot reshape array of size 25 into shape (1,2)

In [58]:
re1 = np.random.randint(1,100,15)

print(re1)

re2 = re1.reshape(5,3)

print(re2)

[77 22 47  9 65 24 40  2 68 90 88  5 27 49 64]
[[77 22 47]
 [ 9 65 24]
 [40  2 68]
 [90 88  5]
 [27 49 64]]


In [63]:
arr =np.array([['a','b','c'],['d','e','f'],['g','h','i']])

print(arr)

print('double = ',arr[2][0]) # double bracket notaion

print('single = ',arr[2,0]) # single bracket notation

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]
single =  g


In [66]:
arr =np.array(['a','b','c','d','e','f','g','h'])

print(arr[2:4])


['c' 'd']


In [ ]:
# 1. Create the same NumPy array using a Python range and a list.
# 2. Using a NumPy function, create a one-dimensional NumPy array of the numbers from 10 to 100,
# counting by 10.
# 3.create a NumPy array of the capital letters, A-Z. (np.array(list(ascii_uppercase))
# 4.create a ten-element NumPy array object of all zeros.
# 5.create a ten-element NumPy array object of all ones.
# 6.find the data type given in question 3.
# 7. create a ten-element array of random integers between 1 and 5 (inclusive).
# 8. Create a 1D array of numbers from 0 to 9.
# OUTPUT: #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# 9.Extract all odd numbers from arr (arr[arr % 2 == 1])
#  Input:arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#  output: #> array([1, 3, 5, 7, 9])
# 10.Replace all odd numbers in arr with -1.
#  Input:arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#  output: #> array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

In [7]:
import pandas as pd
import string

In [ ]:
df = pd.read_csv('ctc.csv')
df

In [ ]:
df.head()

In [17]:
df.shape()


NameError: name 'df' is not defined

In [10]:
a=np.arange(0,10,1)
a[a%2!=0]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [18]:
a=np.array(list(string.ascii_uppercase))

In [19]:
a

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')