In [1]:
import numpy as np

In [2]:
a= np.array(['FCAIT','FCT','FET'])

print(type(a))

print(a)

<class 'numpy.ndarray'>
['FCAIT' 'FCT' 'FET']


In [3]:
b = np.arange(0,10,1)

print(b)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
c = np.zeros(3)

print(c)

c1 = np.zeros((3,3)) #have to give as tuple

print(c1)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
c = np.ones(3)

print(c)

c1 = np.ones((3,3)) #have to give as tuple

print(c1)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
b = np.eye(2)
#b = np.eye(3)

print(b)

In [ ]:
c = np.linspace(0,1,11)

print(c)

In [ ]:

l = [1,5,3,8,2,3,6,7,5,2,9,11,2,5,3,4,8,9,3,1,9,3]

a = np.array(l)

print('Min way1 = ',a.min())

print('Min way2 = ',np.min(a))

In [ ]:
l = [1,5,3,8,2,3,6,7,5,2,9,11,2,5,3,4,8,9,3,1,9,3]

a = np.array(l)

print('Max way1 = ',a.max())

print('Max way2 = ',np.max(a))

In [ ]:
l = [7,5,3,1,8,2,3,6,11,5,2,9,10,2,5,3,7,8,9,3,1,9,3]

a = np.array(l)

print('Min = ',a.min())

print('ArgMin = ',a.argmin())

print('Max = ',a.max())

print('ArgMax = ',a.argmax())

print('Sum = ',a.sum())

print('Mean = ',a.mean())

print('Std = ',a.std())

In [ ]:
array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('sum = ',array2d.sum())

In [ ]:

array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('sum (cols)= ',array2d.sum(axis=0)) #Vertical

print('sum (rows)= ',array2d.sum(axis=1)) #Horizontal

In [ ]:
b = np.zeros((3,3))

print(b.shape)

In [6]:
re1 = np.random.randint(1,100,15)

print(re1)

re2 = re1.reshape(5,3)

print(re2)

[38 19 70 57 45  1  1 48 11  1 89 26 97 10 24]
[[38 19 70]
 [57 45  1]
 [ 1 48 11]
 [ 1 89 26]
 [97 10 24]]


In [ ]:
arr =np.array([['a','b','c'],['d','e','f'],['g','h','i']])

print(arr)

print('double = ',arr[2][0]) # double bracket notaion

print('single = ',arr[2,0]) # single bracket notation

In [ ]:
arr =np.array(['a','b','c','d','e','f','g','h'])

print(arr[2:5])
print(arr[:5])
print(arr[5:])
print(arr[2:7:2])
print(arr[::-1])